/* Generated by Yosys 0.8+498 (git sha1 296ecde6, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

module \../toggle-re.aig (Q, clk, reset, \!Q , enable);
  output \!Q ;
  (* init = 32'd0 *)
  output Q;
  reg Q = 32'd0;
  input clk;
  input enable;
  wire n1_inv;
  wire n4;
  wire n4_inv;
  wire n5;
  wire n5_inv;
  wire n6;
  wire n7;
  input reset;
  always @(posedge clk)
      Q <= n7;
  assign n4 = Q & enable;
  assign n5 = \!Q  & n1_inv;
  assign n6 = n5_inv & n4_inv;
  assign n7 = n6 & reset;
  assign n1_inv = ~enable;
  assign \!Q  = ~Q;
  assign n4_inv = ~n4;
  assign n5_inv = ~n5;
endmodule
