/* Generated by Yosys 0.8+498 (git sha1 296ecde6, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

module \../and.aig (n1, n2, n3);
  input n1;
  input n2;
  output n3;
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _0_ (
    .A(n2),
    .B(n1),
    .Y(n3)
  );
endmodule
