/* Generated by Yosys 0.8+498 (git sha1 296ecde6, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

module \../halfadder.aig (y, s, c, x);
  output c;
  wire n1_inv;
  wire n2_inv;
  wire n3_inv;
  wire n4;
  wire n4_inv;
  output s;
  input x;
  input y;
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _0_ (
    .A(y),
    .B(x),
    .Y(c)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _1_ (
    .A(n2_inv),
    .B(n1_inv),
    .Y(n4)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _2_ (
    .A(n4_inv),
    .B(n3_inv),
    .Y(s)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _3_ (
    .A(x),
    .Y(n1_inv)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _4_ (
    .A(y),
    .Y(n2_inv)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _5_ (
    .A(c),
    .Y(n3_inv)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _6_ (
    .A(n4),
    .Y(n4_inv)
  );
endmodule
