/* Generated by Yosys 0.8+498 (git sha1 296ecde6, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

module \../halfadder.aig (y, s, c, x);
  output c;
  wire n1_inv;
  wire n2_inv;
  wire n3_inv;
  wire n4;
  wire n4_inv;
  output s;
  input x;
  input y;
  assign c = y & x;
  assign n4 = n2_inv & n1_inv;
  assign s = n4_inv & n3_inv;
  assign n1_inv = ~x;
  assign n2_inv = ~y;
  assign n3_inv = ~c;
  assign n4_inv = ~n4;
endmodule
