/* Generated by Yosys 0.8+498 (git sha1 296ecde6, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

module \../or.aig (n1, n2, n3_inv);
  input n1;
  wire n1_inv;
  input n2;
  wire n2_inv;
  wire n3;
  output n3_inv;
  assign n3 = n2_inv & n1_inv;
  assign n1_inv = ~n1;
  assign n2_inv = ~n2;
  assign n3_inv = ~n3;
endmodule
