/* Generated by Yosys 0.8+498 (git sha1 296ecde6, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

module \../or.aig (n1, n2, n3_inv);
  input n1;
  wire n1_inv;
  input n2;
  wire n2_inv;
  wire n3;
  output n3_inv;
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _0_ (
    .A(n2_inv),
    .B(n1_inv),
    .Y(n3)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _1_ (
    .A(n1),
    .Y(n1_inv)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _2_ (
    .A(n2),
    .Y(n2_inv)
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _3_ (
    .A(n3),
    .Y(n3_inv)
  );
endmodule
