/* Generated by Yosys 0.8+498 (git sha1 296ecde6, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

module \../inverter.aig (n1, n1_inv);
  input n1;
  output n1_inv;
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _0_ (
    .A(n1),
    .Y(n1_inv)
  );
endmodule
