/* Generated by Yosys 0.8+498 (git sha1 296ecde6, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

module \../true.aig (n0_inv);
  wire _0_;
  wire _1_;
  wire n0;
  output n0_inv;
  assign _1_ = 1'h1;
  assign n0_inv = _1_;
endmodule
