/* Generated by Yosys 0.8+498 (git sha1 296ecde6, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

module \../notcnt1e.aig (clk, n1);
  input clk;
  input n1;
  wire n1_inv;
  wire n2;
  wire n2_inv;
  wire n3;
  wire n3_inv;
  wire n4;
  wire n4_inv;
  wire n5;
  assign n1_inv = 1'hx;
  assign n2 = 1'h0;
  assign n2_inv = 1'hx;
  assign n3 = 1'hx;
  assign n3_inv = 1'hx;
  assign n4 = 1'hx;
  assign n4_inv = 1'hx;
  assign n5 = 1'hx;
endmodule
